# Generated by Django 5.0.6 on 2024-06-27 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('order_number', models.CharField(max_length=100)),
                ('order_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('on-hold', 'On Hold'), ('processing', 'Processing'), ('partially-shipped', 'Partially Shipped'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('received', 'Received'), ('completed', 'Completed'), ('partially-received', 'Partially Received'), ('returned', 'Returned'), ('refunded', 'Refunded'), ('closed', 'Closed'), ('payment-received', 'Payment Received'), ('awaiting-payment', 'Awaiting Payment')], default='draft', max_length=20)),
                ('supplier_name', models.CharField(max_length=255)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('quantity_ordered', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_category', models.CharField(max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_information', models.TextField()),
                ('payment_terms', models.CharField(choices=[('net 30', 'Net 30'), ('net 60', 'Net 60')], default='net 30', max_length=10)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='credit_card', max_length=20)),
                ('attachments', models.TextField()),
                ('shipping_method', models.CharField(choices=[('ground', 'Ground'), ('air', 'Air'), ('express', 'Express')], default='ground', max_length=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_mgmt.address')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_mgmt.supplier')),
            ],
        ),
    ]
