# Generated by Django 5.0.6 on 2024-06-27 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_holder_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('phone_name', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactaddress', to='supplier_mgmt.address')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplieraddress', to='supplier_mgmt.address')),
                ('bank_details', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierbank', to='supplier_mgmt.bankdetails')),
                ('contact_person_detail', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliercontact', to='supplier_mgmt.contactperson')),
                ('social_links', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierlinks', to='supplier_mgmt.sociallinks')),
            ],
        ),
    ]
