# Generated by Django 5.0.6 on 2024-06-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='name',
        ),
    ]
