# Generated by Django 5.0.6 on 2024-06-27 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_mgmt', '0002_remove_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplieraddress', to='supplier_mgmt.address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bank_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierbank', to='supplier_mgmt.bankdetails'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliercontact', to='supplier_mgmt.contactperson'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='social_links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierlinks', to='supplier_mgmt.sociallinks'),
        ),
    ]
