# Generated by Django 5.0.6 on 2024-07-01 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_mgmt', '0004_rename_phone_name_contactperson_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='supplier_mgmt.address'),
        ),
    ]
